package com.salus.healthytable.service.allergen;
public enum DeclarationCoverageReason {
    LISTED_IN_EFFECTIVE_RULE, NOT_IN_EFFECTIVE_RULE, PROPOSED_ONLY,
    EXEMPT_SINGLE_INGREDIENT_NAME_MATCH, EXEMPT_MEAT_NAME_MATCH,
    APPLICABLE_DATE_UNKNOWN, RULESET_NOT_FOUND, PRODUCT_CONTEXT_INSUFFICIENT,
    SULFITE_THRESHOLD_MET, SULFITE_THRESHOLD_NOT_MET, SULFITE_THRESHOLD_UNKNOWN,
    SULFITE_NOT_ADDED, SULFITE_ADDITION_UNKNOWN
}
